### ISSUE TITLE
What's about the progress?  

### ISSUE THREAD

**Issue by ajsb85** [zachariahtimothy/magento-rest#1]
Can you share the ownership to me? if you cannot continue, thanks.

**Comment by zachariahtimothy** [comment]
I had to switch my focus from our Magento 1.9 > Magento 2.0 migration to our internal management software, but I would welcome the help. Note that it was too frustrating integrating with Magento 1.9 and since it is deprecated I chose to focus on integrating with Magento 2 which is fun and not frustrating because the endpoints work as one would expect. I will give you access, and note that Magento 2 is on the magento2 branch, and I am not in love with the way I was structuring it so happy to change that too.

**Comment by ajsb85** [comment]
Very good, add me as contributor @ajsb85
I can show you my experiences with ECMA 6 and Magento 2 REST API.

**Comment by zachariahtimothy** [comment]
That sounds great! My overall goal is to have Magento as the e-commerce front-end for my website, but I have a separate management software that manages catalog, orders, etc, then pushes data to Magento, Amazon, Ebay, etc. It is written in Meteor JS so whatever solution we come up with needs to be able to be ported to work with Meteor, which should not be a big deal.

**Comment by ajsb85** [comment]
Very good, add me as collaborator.
I need the module for own CMS. 
https://github.com/zachariahtimothy/magento-rest/settings/collaboration

**Comment by zachariahtimothy** [comment]
Yep I did add you as a collaborator. You should be good to go.

_____________________________________
Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis <https://twitter.com/#!/@zachariahCurtis>
